server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: authorservice
          uri: http://localhost:8082
          predicates:
            - Path=/authors/**, 
        - id: menuscriptservice
          uri: http://localhost:8083
          predicates:
            - Path=/manuscripts/**, 
        - id: aiservice
          uri: http://localhost:8084
          predicates:
            - Path=/publishings/**, 
        - id: userservice
          uri: http://localhost:8085
          predicates:
            - Path=/userInfos/**, 
        - id: libraryservice
          uri: http://localhost:8086
          predicates:
            - Path=/books/**, /getBooks/**
        - id: pointservice
          uri: http://localhost:8087
          predicates:
            - Path=/points/**, /getPoints/**
        - id: applyservice
          uri: http://localhost:8088
          predicates:
            - Path=/applyings/**, /getStars/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: authorservice
          uri: http://authorservice:8080
          predicates:
            - Path=/authors/**, 
        - id: menuscriptservice
          uri: http://menuscriptservice:8080
          predicates:
            - Path=/manuscripts/**, 
        - id: aiservice
          uri: http://aiservice:8080
          predicates:
            - Path=/publishings/**, 
        - id: userservice
          uri: http://userservice:8080
          predicates:
            - Path=/userInfos/**, 
        - id: libraryservice
          uri: http://libraryservice:8080
          predicates:
            - Path=/books/**, 
        - id: pointservice
          uri: http://pointservice:8080
          predicates:
            - Path=/points/**, 
        - id: applyservice
          uri: http://applyservice:8080
          predicates:
            - Path=/applyings/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
